name: notes_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  drift: ^2.20.0
  drift_flutter: ^0.1.0
  device_preview: ^1.2.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  intl: ^0.19.0
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^3.0.0
  drift_dev: ^2.20.0
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
